/*
 * Generated by gdbus-codegen 2.32.1. DO NOT EDIT.
 *
 * The license of this code is the same as for the source it was derived from.
 */

#ifdef HAVE_CONFIG_H
#  include "config.h"
#endif

#include "bamf-gdbus-browser-generated.h"

#ifdef G_OS_UNIX
#  include <gio/gunixfdlist.h>
#endif

typedef struct
{
  GDBusArgInfo parent_struct;
  gboolean use_gvariant;
} _ExtendedGDBusArgInfo;

typedef struct
{
  GDBusMethodInfo parent_struct;
  const gchar *signal_name;
  gboolean pass_fdlist;
} _ExtendedGDBusMethodInfo;

typedef struct
{
  GDBusSignalInfo parent_struct;
  const gchar *signal_name;
} _ExtendedGDBusSignalInfo;

typedef struct
{
  GDBusPropertyInfo parent_struct;
  const gchar *hyphen_name;
  gboolean use_gvariant;
} _ExtendedGDBusPropertyInfo;

typedef struct
{
  GDBusInterfaceInfo parent_struct;
  const gchar *hyphen_name;
} _ExtendedGDBusInterfaceInfo;

typedef struct
{
  const _ExtendedGDBusPropertyInfo *info;
  guint prop_id;
  GValue orig_value; /* the value before the change */
} ChangedProperty;

static void
_changed_property_free (ChangedProperty *data)
{
  g_value_unset (&data->orig_value);
  g_free (data);
}

static gboolean
_g_strv_equal0 (gchar **a, gchar **b)
{
  gboolean ret = FALSE;
  guint n;
  if (a == NULL && b == NULL)
    {
      ret = TRUE;
      goto out;
    }
  if (a == NULL || b == NULL)
    goto out;
  if (g_strv_length (a) != g_strv_length (b))
    goto out;
  for (n = 0; a[n] != NULL; n++)
    if (g_strcmp0 (a[n], b[n]) != 0)
      goto out;
  ret = TRUE;
out:
  return ret;
}

static gboolean
_g_variant_equal0 (GVariant *a, GVariant *b)
{
  gboolean ret = FALSE;
  if (a == NULL && b == NULL)
    {
      ret = TRUE;
      goto out;
    }
  if (a == NULL || b == NULL)
    goto out;
  ret = g_variant_equal (a, b);
out:
  return ret;
}

G_GNUC_UNUSED static gboolean
_g_value_equal (const GValue *a, const GValue *b)
{
  gboolean ret = FALSE;
  g_assert (G_VALUE_TYPE (a) == G_VALUE_TYPE (b));
  switch (G_VALUE_TYPE (a))
    {
      case G_TYPE_BOOLEAN:
        ret = (g_value_get_boolean (a) == g_value_get_boolean (b));
        break;
      case G_TYPE_UCHAR:
        ret = (g_value_get_uchar (a) == g_value_get_uchar (b));
        break;
      case G_TYPE_INT:
        ret = (g_value_get_int (a) == g_value_get_int (b));
        break;
      case G_TYPE_UINT:
        ret = (g_value_get_uint (a) == g_value_get_uint (b));
        break;
      case G_TYPE_INT64:
        ret = (g_value_get_int64 (a) == g_value_get_int64 (b));
        break;
      case G_TYPE_UINT64:
        ret = (g_value_get_uint64 (a) == g_value_get_uint64 (b));
        break;
      case G_TYPE_DOUBLE:
        ret = (g_value_get_double (a) == g_value_get_double (b));
        break;
      case G_TYPE_STRING:
        ret = (g_strcmp0 (g_value_get_string (a), g_value_get_string (b)) == 0);
        break;
      case G_TYPE_VARIANT:
        ret = _g_variant_equal0 (g_value_get_variant (a), g_value_get_variant (b));
        break;
      default:
        if (G_VALUE_TYPE (a) == G_TYPE_STRV)
          ret = _g_strv_equal0 (g_value_get_boxed (a), g_value_get_boxed (b));
        else
          g_critical ("_g_value_equal() does not handle type %s", g_type_name (G_VALUE_TYPE (a)));
        break;
    }
  return ret;
}

/* ------------------------------------------------------------------------
 * Code for interface org.ayatana.bamf.browser
 * ------------------------------------------------------------------------
 */

/**
 * SECTION:BamfDBusBrowser
 * @title: BamfDBusBrowser
 * @short_description: Generated C code for the org.ayatana.bamf.browser D-Bus interface
 *
 * This section contains code for working with the <link linkend="gdbus-interface-org-ayatana-bamf-browser.top_of_page">org.ayatana.bamf.browser</link> D-Bus interface in C.
 */

/* ---- Introspection data for org.ayatana.bamf.browser ---- */

static const _ExtendedGDBusArgInfo _bamf_dbus_browser__method_info_tab_ids_OUT_ARG_ids =
{
  {
    -1,
    "ids",
    "as",
    NULL
  },
  FALSE
};

static const _ExtendedGDBusArgInfo * const _bamf_dbus_browser__method_info_tab_ids_OUT_ARG_pointers[] =
{
  &_bamf_dbus_browser__method_info_tab_ids_OUT_ARG_ids,
  NULL
};

static const _ExtendedGDBusMethodInfo _bamf_dbus_browser__method_info_tab_ids =
{
  {
    -1,
    "TabIds",
    NULL,
    (GDBusArgInfo **) &_bamf_dbus_browser__method_info_tab_ids_OUT_ARG_pointers,
    NULL
  },
  "handle-tab-ids",
  FALSE
};

static const _ExtendedGDBusArgInfo _bamf_dbus_browser__method_info_show_tab_IN_ARG_id =
{
  {
    -1,
    "id",
    "s",
    NULL
  },
  FALSE
};

static const _ExtendedGDBusArgInfo * const _bamf_dbus_browser__method_info_show_tab_IN_ARG_pointers[] =
{
  &_bamf_dbus_browser__method_info_show_tab_IN_ARG_id,
  NULL
};

static const _ExtendedGDBusMethodInfo _bamf_dbus_browser__method_info_show_tab =
{
  {
    -1,
    "ShowTab",
    (GDBusArgInfo **) &_bamf_dbus_browser__method_info_show_tab_IN_ARG_pointers,
    NULL,
    NULL
  },
  "handle-show-tab",
  FALSE
};

static const _ExtendedGDBusArgInfo _bamf_dbus_browser__method_info_tab_uri_IN_ARG_id =
{
  {
    -1,
    "id",
    "s",
    NULL
  },
  FALSE
};

static const _ExtendedGDBusArgInfo * const _bamf_dbus_browser__method_info_tab_uri_IN_ARG_pointers[] =
{
  &_bamf_dbus_browser__method_info_tab_uri_IN_ARG_id,
  NULL
};

static const _ExtendedGDBusArgInfo _bamf_dbus_browser__method_info_tab_uri_OUT_ARG_uri =
{
  {
    -1,
    "uri",
    "s",
    NULL
  },
  FALSE
};

static const _ExtendedGDBusArgInfo * const _bamf_dbus_browser__method_info_tab_uri_OUT_ARG_pointers[] =
{
  &_bamf_dbus_browser__method_info_tab_uri_OUT_ARG_uri,
  NULL
};

static const _ExtendedGDBusMethodInfo _bamf_dbus_browser__method_info_tab_uri =
{
  {
    -1,
    "TabUri",
    (GDBusArgInfo **) &_bamf_dbus_browser__method_info_tab_uri_IN_ARG_pointers,
    (GDBusArgInfo **) &_bamf_dbus_browser__method_info_tab_uri_OUT_ARG_pointers,
    NULL
  },
  "handle-tab-uri",
  FALSE
};

static const _ExtendedGDBusArgInfo _bamf_dbus_browser__method_info_tab_preview_IN_ARG_id =
{
  {
    -1,
    "id",
    "s",
    NULL
  },
  FALSE
};

static const _ExtendedGDBusArgInfo * const _bamf_dbus_browser__method_info_tab_preview_IN_ARG_pointers[] =
{
  &_bamf_dbus_browser__method_info_tab_preview_IN_ARG_id,
  NULL
};

static const _ExtendedGDBusArgInfo _bamf_dbus_browser__method_info_tab_preview_OUT_ARG_preview =
{
  {
    -1,
    "preview",
    "ay",
    NULL
  },
  FALSE
};

static const _ExtendedGDBusArgInfo * const _bamf_dbus_browser__method_info_tab_preview_OUT_ARG_pointers[] =
{
  &_bamf_dbus_browser__method_info_tab_preview_OUT_ARG_preview,
  NULL
};

static const _ExtendedGDBusMethodInfo _bamf_dbus_browser__method_info_tab_preview =
{
  {
    -1,
    "TabPreview",
    (GDBusArgInfo **) &_bamf_dbus_browser__method_info_tab_preview_IN_ARG_pointers,
    (GDBusArgInfo **) &_bamf_dbus_browser__method_info_tab_preview_OUT_ARG_pointers,
    NULL
  },
  "handle-tab-preview",
  FALSE
};

static const _ExtendedGDBusArgInfo _bamf_dbus_browser__method_info_tab_xid_IN_ARG_id =
{
  {
    -1,
    "id",
    "s",
    NULL
  },
  FALSE
};

static const _ExtendedGDBusArgInfo * const _bamf_dbus_browser__method_info_tab_xid_IN_ARG_pointers[] =
{
  &_bamf_dbus_browser__method_info_tab_xid_IN_ARG_id,
  NULL
};

static const _ExtendedGDBusArgInfo _bamf_dbus_browser__method_info_tab_xid_OUT_ARG_xid =
{
  {
    -1,
    "xid",
    "u",
    NULL
  },
  FALSE
};

static const _ExtendedGDBusArgInfo * const _bamf_dbus_browser__method_info_tab_xid_OUT_ARG_pointers[] =
{
  &_bamf_dbus_browser__method_info_tab_xid_OUT_ARG_xid,
  NULL
};

static const _ExtendedGDBusMethodInfo _bamf_dbus_browser__method_info_tab_xid =
{
  {
    -1,
    "TabXid",
    (GDBusArgInfo **) &_bamf_dbus_browser__method_info_tab_xid_IN_ARG_pointers,
    (GDBusArgInfo **) &_bamf_dbus_browser__method_info_tab_xid_OUT_ARG_pointers,
    NULL
  },
  "handle-tab-xid",
  FALSE
};

static const _ExtendedGDBusMethodInfo * const _bamf_dbus_browser__method_info_pointers[] =
{
  &_bamf_dbus_browser__method_info_tab_ids,
  &_bamf_dbus_browser__method_info_show_tab,
  &_bamf_dbus_browser__method_info_tab_uri,
  &_bamf_dbus_browser__method_info_tab_preview,
  &_bamf_dbus_browser__method_info_tab_xid,
  NULL
};

static const _ExtendedGDBusArgInfo _bamf_dbus_browser__signal_info_tab_opened_ARG_id =
{
  {
    -1,
    "id",
    "s",
    NULL
  },
  FALSE
};

static const _ExtendedGDBusArgInfo * const _bamf_dbus_browser__signal_info_tab_opened_ARG_pointers[] =
{
  &_bamf_dbus_browser__signal_info_tab_opened_ARG_id,
  NULL
};

static const _ExtendedGDBusSignalInfo _bamf_dbus_browser__signal_info_tab_opened =
{
  {
    -1,
    "TabOpened",
    (GDBusArgInfo **) &_bamf_dbus_browser__signal_info_tab_opened_ARG_pointers,
    NULL
  },
  "tab-opened"
};

static const _ExtendedGDBusArgInfo _bamf_dbus_browser__signal_info_tab_closed_ARG_id =
{
  {
    -1,
    "id",
    "s",
    NULL
  },
  FALSE
};

static const _ExtendedGDBusArgInfo * const _bamf_dbus_browser__signal_info_tab_closed_ARG_pointers[] =
{
  &_bamf_dbus_browser__signal_info_tab_closed_ARG_id,
  NULL
};

static const _ExtendedGDBusSignalInfo _bamf_dbus_browser__signal_info_tab_closed =
{
  {
    -1,
    "TabClosed",
    (GDBusArgInfo **) &_bamf_dbus_browser__signal_info_tab_closed_ARG_pointers,
    NULL
  },
  "tab-closed"
};

static const _ExtendedGDBusArgInfo _bamf_dbus_browser__signal_info_tab_uri_changed_ARG_id =
{
  {
    -1,
    "id",
    "s",
    NULL
  },
  FALSE
};

static const _ExtendedGDBusArgInfo _bamf_dbus_browser__signal_info_tab_uri_changed_ARG_old_uri =
{
  {
    -1,
    "old_uri",
    "s",
    NULL
  },
  FALSE
};

static const _ExtendedGDBusArgInfo _bamf_dbus_browser__signal_info_tab_uri_changed_ARG_new_uri =
{
  {
    -1,
    "new_uri",
    "s",
    NULL
  },
  FALSE
};

static const _ExtendedGDBusArgInfo * const _bamf_dbus_browser__signal_info_tab_uri_changed_ARG_pointers[] =
{
  &_bamf_dbus_browser__signal_info_tab_uri_changed_ARG_id,
  &_bamf_dbus_browser__signal_info_tab_uri_changed_ARG_old_uri,
  &_bamf_dbus_browser__signal_info_tab_uri_changed_ARG_new_uri,
  NULL
};

static const _ExtendedGDBusSignalInfo _bamf_dbus_browser__signal_info_tab_uri_changed =
{
  {
    -1,
    "TabUriChanged",
    (GDBusArgInfo **) &_bamf_dbus_browser__signal_info_tab_uri_changed_ARG_pointers,
    NULL
  },
  "tab-uri-changed"
};

static const _ExtendedGDBusSignalInfo * const _bamf_dbus_browser__signal_info_pointers[] =
{
  &_bamf_dbus_browser__signal_info_tab_opened,
  &_bamf_dbus_browser__signal_info_tab_closed,
  &_bamf_dbus_browser__signal_info_tab_uri_changed,
  NULL
};

static const _ExtendedGDBusInterfaceInfo _bamf_dbus_browser__interface_info =
{
  {
    -1,
    "org.ayatana.bamf.browser",
    (GDBusMethodInfo **) &_bamf_dbus_browser__method_info_pointers,
    (GDBusSignalInfo **) &_bamf_dbus_browser__signal_info_pointers,
    NULL,
    NULL
  },
  "",
};


/**
 * bamf_dbus_browser__interface_info:
 *
 * Gets a machine-readable description of the <link linkend="gdbus-interface-org-ayatana-bamf-browser.top_of_page">org.ayatana.bamf.browser</link> D-Bus interface.
 *
 * Returns: (transfer none): A #GDBusInterfaceInfo. Do not free.
 */
GDBusInterfaceInfo *
bamf_dbus_browser__interface_info (void)
{
  return (GDBusInterfaceInfo *) &_bamf_dbus_browser__interface_info;
}

/**
 * bamf_dbus_browser__override_properties:
 * @klass: The class structure for a #GObject<!-- -->-derived class.
 * @property_id_begin: The property id to assign to the first overridden property.
 *
 * Overrides all #GObject properties in the #BamfDBusBrowser interface for a concrete class.
 * The properties are overridden in the order they are defined.
 *
 * Returns: The last property id.
 */
guint
bamf_dbus_browser__override_properties (GObjectClass *klass, guint property_id_begin)
{
  return property_id_begin - 1;
}



/**
 * BamfDBusBrowser:
 *
 * Abstract interface type for the D-Bus interface <link linkend="gdbus-interface-org-ayatana-bamf-browser.top_of_page">org.ayatana.bamf.browser</link>.
 */

/**
 * BamfDBusBrowserIface:
 * @parent_iface: The parent interface.
 * @handle_show_tab: Handler for the #BamfDBusBrowser::handle-show-tab signal.
 * @handle_tab_ids: Handler for the #BamfDBusBrowser::handle-tab-ids signal.
 * @handle_tab_preview: Handler for the #BamfDBusBrowser::handle-tab-preview signal.
 * @handle_tab_uri: Handler for the #BamfDBusBrowser::handle-tab-uri signal.
 * @handle_tab_xid: Handler for the #BamfDBusBrowser::handle-tab-xid signal.
 * @tab_closed: Handler for the #BamfDBusBrowser::tab-closed signal.
 * @tab_opened: Handler for the #BamfDBusBrowser::tab-opened signal.
 * @tab_uri_changed: Handler for the #BamfDBusBrowser::tab-uri-changed signal.
 *
 * Virtual table for the D-Bus interface <link linkend="gdbus-interface-org-ayatana-bamf-browser.top_of_page">org.ayatana.bamf.browser</link>.
 */

static void
bamf_dbus_browser__default_init (BamfDBusBrowserIface *iface)
{
  /* GObject signals for incoming D-Bus method calls: */
  /**
   * BamfDBusBrowser::handle-tab-ids:
   * @object: A #BamfDBusBrowser.
   * @invocation: A #GDBusMethodInvocation.
   *
   * Signal emitted when a remote caller is invoking the <link linkend="gdbus-method-org-ayatana-bamf-browser.TabIds">TabIds()</link> D-Bus method.
   *
   * If a signal handler returns %TRUE, it means the signal handler will handle the invocation (e.g. take a reference to @invocation and eventually call bamf_dbus_browser__complete_tab_ids() or e.g. g_dbus_method_invocation_return_error() on it) and no order signal handlers will run. If no signal handler handles the invocation, the %G_DBUS_ERROR_UNKNOWN_METHOD error is returned.
   *
   * Returns: %TRUE if the invocation was handled, %FALSE to let other signal handlers run.
   */
  g_signal_new ("handle-tab-ids",
    G_TYPE_FROM_INTERFACE (iface),
    G_SIGNAL_RUN_LAST,
    G_STRUCT_OFFSET (BamfDBusBrowserIface, handle_tab_ids),
    g_signal_accumulator_true_handled,
    NULL,
    g_cclosure_marshal_generic,
    G_TYPE_BOOLEAN,
    1,
    G_TYPE_DBUS_METHOD_INVOCATION);

  /**
   * BamfDBusBrowser::handle-show-tab:
   * @object: A #BamfDBusBrowser.
   * @invocation: A #GDBusMethodInvocation.
   * @arg_id: Argument passed by remote caller.
   *
   * Signal emitted when a remote caller is invoking the <link linkend="gdbus-method-org-ayatana-bamf-browser.ShowTab">ShowTab()</link> D-Bus method.
   *
   * If a signal handler returns %TRUE, it means the signal handler will handle the invocation (e.g. take a reference to @invocation and eventually call bamf_dbus_browser__complete_show_tab() or e.g. g_dbus_method_invocation_return_error() on it) and no order signal handlers will run. If no signal handler handles the invocation, the %G_DBUS_ERROR_UNKNOWN_METHOD error is returned.
   *
   * Returns: %TRUE if the invocation was handled, %FALSE to let other signal handlers run.
   */
  g_signal_new ("handle-show-tab",
    G_TYPE_FROM_INTERFACE (iface),
    G_SIGNAL_RUN_LAST,
    G_STRUCT_OFFSET (BamfDBusBrowserIface, handle_show_tab),
    g_signal_accumulator_true_handled,
    NULL,
    g_cclosure_marshal_generic,
    G_TYPE_BOOLEAN,
    2,
    G_TYPE_DBUS_METHOD_INVOCATION, G_TYPE_STRING);

  /**
   * BamfDBusBrowser::handle-tab-uri:
   * @object: A #BamfDBusBrowser.
   * @invocation: A #GDBusMethodInvocation.
   * @arg_id: Argument passed by remote caller.
   *
   * Signal emitted when a remote caller is invoking the <link linkend="gdbus-method-org-ayatana-bamf-browser.TabUri">TabUri()</link> D-Bus method.
   *
   * If a signal handler returns %TRUE, it means the signal handler will handle the invocation (e.g. take a reference to @invocation and eventually call bamf_dbus_browser__complete_tab_uri() or e.g. g_dbus_method_invocation_return_error() on it) and no order signal handlers will run. If no signal handler handles the invocation, the %G_DBUS_ERROR_UNKNOWN_METHOD error is returned.
   *
   * Returns: %TRUE if the invocation was handled, %FALSE to let other signal handlers run.
   */
  g_signal_new ("handle-tab-uri",
    G_TYPE_FROM_INTERFACE (iface),
    G_SIGNAL_RUN_LAST,
    G_STRUCT_OFFSET (BamfDBusBrowserIface, handle_tab_uri),
    g_signal_accumulator_true_handled,
    NULL,
    g_cclosure_marshal_generic,
    G_TYPE_BOOLEAN,
    2,
    G_TYPE_DBUS_METHOD_INVOCATION, G_TYPE_STRING);

  /**
   * BamfDBusBrowser::handle-tab-preview:
   * @object: A #BamfDBusBrowser.
   * @invocation: A #GDBusMethodInvocation.
   * @arg_id: Argument passed by remote caller.
   *
   * Signal emitted when a remote caller is invoking the <link linkend="gdbus-method-org-ayatana-bamf-browser.TabPreview">TabPreview()</link> D-Bus method.
   *
   * If a signal handler returns %TRUE, it means the signal handler will handle the invocation (e.g. take a reference to @invocation and eventually call bamf_dbus_browser__complete_tab_preview() or e.g. g_dbus_method_invocation_return_error() on it) and no order signal handlers will run. If no signal handler handles the invocation, the %G_DBUS_ERROR_UNKNOWN_METHOD error is returned.
   *
   * Returns: %TRUE if the invocation was handled, %FALSE to let other signal handlers run.
   */
  g_signal_new ("handle-tab-preview",
    G_TYPE_FROM_INTERFACE (iface),
    G_SIGNAL_RUN_LAST,
    G_STRUCT_OFFSET (BamfDBusBrowserIface, handle_tab_preview),
    g_signal_accumulator_true_handled,
    NULL,
    g_cclosure_marshal_generic,
    G_TYPE_BOOLEAN,
    2,
    G_TYPE_DBUS_METHOD_INVOCATION, G_TYPE_STRING);

  /**
   * BamfDBusBrowser::handle-tab-xid:
   * @object: A #BamfDBusBrowser.
   * @invocation: A #GDBusMethodInvocation.
   * @arg_id: Argument passed by remote caller.
   *
   * Signal emitted when a remote caller is invoking the <link linkend="gdbus-method-org-ayatana-bamf-browser.TabXid">TabXid()</link> D-Bus method.
   *
   * If a signal handler returns %TRUE, it means the signal handler will handle the invocation (e.g. take a reference to @invocation and eventually call bamf_dbus_browser__complete_tab_xid() or e.g. g_dbus_method_invocation_return_error() on it) and no order signal handlers will run. If no signal handler handles the invocation, the %G_DBUS_ERROR_UNKNOWN_METHOD error is returned.
   *
   * Returns: %TRUE if the invocation was handled, %FALSE to let other signal handlers run.
   */
  g_signal_new ("handle-tab-xid",
    G_TYPE_FROM_INTERFACE (iface),
    G_SIGNAL_RUN_LAST,
    G_STRUCT_OFFSET (BamfDBusBrowserIface, handle_tab_xid),
    g_signal_accumulator_true_handled,
    NULL,
    g_cclosure_marshal_generic,
    G_TYPE_BOOLEAN,
    2,
    G_TYPE_DBUS_METHOD_INVOCATION, G_TYPE_STRING);

  /* GObject signals for received D-Bus signals: */
  /**
   * BamfDBusBrowser::tab-opened:
   * @object: A #BamfDBusBrowser.
   * @arg_id: Argument.
   *
   * On the client-side, this signal is emitted whenever the D-Bus signal <link linkend="gdbus-signal-org-ayatana-bamf-browser.TabOpened">"TabOpened"</link> is received.
   *
   * On the service-side, this signal can be used with e.g. g_signal_emit_by_name() to make the object emit the D-Bus signal.
   */
  g_signal_new ("tab-opened",
    G_TYPE_FROM_INTERFACE (iface),
    G_SIGNAL_RUN_LAST,
    G_STRUCT_OFFSET (BamfDBusBrowserIface, tab_opened),
    NULL,
    NULL,
    g_cclosure_marshal_generic,
    G_TYPE_NONE,
    1, G_TYPE_STRING);

  /**
   * BamfDBusBrowser::tab-closed:
   * @object: A #BamfDBusBrowser.
   * @arg_id: Argument.
   *
   * On the client-side, this signal is emitted whenever the D-Bus signal <link linkend="gdbus-signal-org-ayatana-bamf-browser.TabClosed">"TabClosed"</link> is received.
   *
   * On the service-side, this signal can be used with e.g. g_signal_emit_by_name() to make the object emit the D-Bus signal.
   */
  g_signal_new ("tab-closed",
    G_TYPE_FROM_INTERFACE (iface),
    G_SIGNAL_RUN_LAST,
    G_STRUCT_OFFSET (BamfDBusBrowserIface, tab_closed),
    NULL,
    NULL,
    g_cclosure_marshal_generic,
    G_TYPE_NONE,
    1, G_TYPE_STRING);

  /**
   * BamfDBusBrowser::tab-uri-changed:
   * @object: A #BamfDBusBrowser.
   * @arg_id: Argument.
   * @arg_old_uri: Argument.
   * @arg_new_uri: Argument.
   *
   * On the client-side, this signal is emitted whenever the D-Bus signal <link linkend="gdbus-signal-org-ayatana-bamf-browser.TabUriChanged">"TabUriChanged"</link> is received.
   *
   * On the service-side, this signal can be used with e.g. g_signal_emit_by_name() to make the object emit the D-Bus signal.
   */
  g_signal_new ("tab-uri-changed",
    G_TYPE_FROM_INTERFACE (iface),
    G_SIGNAL_RUN_LAST,
    G_STRUCT_OFFSET (BamfDBusBrowserIface, tab_uri_changed),
    NULL,
    NULL,
    g_cclosure_marshal_generic,
    G_TYPE_NONE,
    3, G_TYPE_STRING, G_TYPE_STRING, G_TYPE_STRING);

}

typedef BamfDBusBrowserIface BamfDBusBrowserInterface;
G_DEFINE_INTERFACE (BamfDBusBrowser, bamf_dbus_browser_, G_TYPE_OBJECT);

/**
 * bamf_dbus_browser__emit_tab_opened:
 * @object: A #BamfDBusBrowser.
 * @arg_id: Argument to pass with the signal.
 *
 * Emits the <link linkend="gdbus-signal-org-ayatana-bamf-browser.TabOpened">"TabOpened"</link> D-Bus signal.
 */
void
bamf_dbus_browser__emit_tab_opened (
    BamfDBusBrowser *object,
    const gchar *arg_id)
{
  g_signal_emit_by_name (object, "tab-opened", arg_id);
}

/**
 * bamf_dbus_browser__emit_tab_closed:
 * @object: A #BamfDBusBrowser.
 * @arg_id: Argument to pass with the signal.
 *
 * Emits the <link linkend="gdbus-signal-org-ayatana-bamf-browser.TabClosed">"TabClosed"</link> D-Bus signal.
 */
void
bamf_dbus_browser__emit_tab_closed (
    BamfDBusBrowser *object,
    const gchar *arg_id)
{
  g_signal_emit_by_name (object, "tab-closed", arg_id);
}

/**
 * bamf_dbus_browser__emit_tab_uri_changed:
 * @object: A #BamfDBusBrowser.
 * @arg_id: Argument to pass with the signal.
 * @arg_old_uri: Argument to pass with the signal.
 * @arg_new_uri: Argument to pass with the signal.
 *
 * Emits the <link linkend="gdbus-signal-org-ayatana-bamf-browser.TabUriChanged">"TabUriChanged"</link> D-Bus signal.
 */
void
bamf_dbus_browser__emit_tab_uri_changed (
    BamfDBusBrowser *object,
    const gchar *arg_id,
    const gchar *arg_old_uri,
    const gchar *arg_new_uri)
{
  g_signal_emit_by_name (object, "tab-uri-changed", arg_id, arg_old_uri, arg_new_uri);
}

/**
 * bamf_dbus_browser__call_tab_ids:
 * @proxy: A #BamfDBusBrowserProxy.
 * @cancellable: (allow-none): A #GCancellable or %NULL.
 * @callback: A #GAsyncReadyCallback to call when the request is satisfied or %NULL.
 * @user_data: User data to pass to @callback.
 *
 * Asynchronously invokes the <link linkend="gdbus-method-org-ayatana-bamf-browser.TabIds">TabIds()</link> D-Bus method on @proxy.
 * When the operation is finished, @callback will be invoked in the <link linkend="g-main-context-push-thread-default">thread-default main loop</link> of the thread you are calling this method from.
 * You can then call bamf_dbus_browser__call_tab_ids_finish() to get the result of the operation.
 *
 * See bamf_dbus_browser__call_tab_ids_sync() for the synchronous, blocking version of this method.
 */
void
bamf_dbus_browser__call_tab_ids (
    BamfDBusBrowser *proxy,
    GCancellable *cancellable,
    GAsyncReadyCallback callback,
    gpointer user_data)
{
  g_dbus_proxy_call (G_DBUS_PROXY (proxy),
    "TabIds",
    g_variant_new ("()"),
    G_DBUS_CALL_FLAGS_NONE,
    -1,
    cancellable,
    callback,
    user_data);
}

/**
 * bamf_dbus_browser__call_tab_ids_finish:
 * @proxy: A #BamfDBusBrowserProxy.
 * @out_ids: (out): Return location for return parameter or %NULL to ignore.
 * @res: The #GAsyncResult obtained from the #GAsyncReadyCallback passed to bamf_dbus_browser__call_tab_ids().
 * @error: Return location for error or %NULL.
 *
 * Finishes an operation started with bamf_dbus_browser__call_tab_ids().
 *
 * Returns: (skip): %TRUE if the call succeded, %FALSE if @error is set.
 */
gboolean
bamf_dbus_browser__call_tab_ids_finish (
    BamfDBusBrowser *proxy,
    gchar ***out_ids,
    GAsyncResult *res,
    GError **error)
{
  GVariant *_ret;
  _ret = g_dbus_proxy_call_finish (G_DBUS_PROXY (proxy), res, error);
  if (_ret == NULL)
    goto _out;
  g_variant_get (_ret,
                 "(^as)",
                 out_ids);
  g_variant_unref (_ret);
_out:
  return _ret != NULL;
}

/**
 * bamf_dbus_browser__call_tab_ids_sync:
 * @proxy: A #BamfDBusBrowserProxy.
 * @out_ids: (out): Return location for return parameter or %NULL to ignore.
 * @cancellable: (allow-none): A #GCancellable or %NULL.
 * @error: Return location for error or %NULL.
 *
 * Synchronously invokes the <link linkend="gdbus-method-org-ayatana-bamf-browser.TabIds">TabIds()</link> D-Bus method on @proxy. The calling thread is blocked until a reply is received.
 *
 * See bamf_dbus_browser__call_tab_ids() for the asynchronous version of this method.
 *
 * Returns: (skip): %TRUE if the call succeded, %FALSE if @error is set.
 */
gboolean
bamf_dbus_browser__call_tab_ids_sync (
    BamfDBusBrowser *proxy,
    gchar ***out_ids,
    GCancellable *cancellable,
    GError **error)
{
  GVariant *_ret;
  _ret = g_dbus_proxy_call_sync (G_DBUS_PROXY (proxy),
    "TabIds",
    g_variant_new ("()"),
    G_DBUS_CALL_FLAGS_NONE,
    -1,
    cancellable,
    error);
  if (_ret == NULL)
    goto _out;
  g_variant_get (_ret,
                 "(^as)",
                 out_ids);
  g_variant_unref (_ret);
_out:
  return _ret != NULL;
}

/**
 * bamf_dbus_browser__call_show_tab:
 * @proxy: A #BamfDBusBrowserProxy.
 * @arg_id: Argument to pass with the method invocation.
 * @cancellable: (allow-none): A #GCancellable or %NULL.
 * @callback: A #GAsyncReadyCallback to call when the request is satisfied or %NULL.
 * @user_data: User data to pass to @callback.
 *
 * Asynchronously invokes the <link linkend="gdbus-method-org-ayatana-bamf-browser.ShowTab">ShowTab()</link> D-Bus method on @proxy.
 * When the operation is finished, @callback will be invoked in the <link linkend="g-main-context-push-thread-default">thread-default main loop</link> of the thread you are calling this method from.
 * You can then call bamf_dbus_browser__call_show_tab_finish() to get the result of the operation.
 *
 * See bamf_dbus_browser__call_show_tab_sync() for the synchronous, blocking version of this method.
 */
void
bamf_dbus_browser__call_show_tab (
    BamfDBusBrowser *proxy,
    const gchar *arg_id,
    GCancellable *cancellable,
    GAsyncReadyCallback callback,
    gpointer user_data)
{
  g_dbus_proxy_call (G_DBUS_PROXY (proxy),
    "ShowTab",
    g_variant_new ("(s)",
                   arg_id),
    G_DBUS_CALL_FLAGS_NONE,
    -1,
    cancellable,
    callback,
    user_data);
}

/**
 * bamf_dbus_browser__call_show_tab_finish:
 * @proxy: A #BamfDBusBrowserProxy.
 * @res: The #GAsyncResult obtained from the #GAsyncReadyCallback passed to bamf_dbus_browser__call_show_tab().
 * @error: Return location for error or %NULL.
 *
 * Finishes an operation started with bamf_dbus_browser__call_show_tab().
 *
 * Returns: (skip): %TRUE if the call succeded, %FALSE if @error is set.
 */
gboolean
bamf_dbus_browser__call_show_tab_finish (
    BamfDBusBrowser *proxy,
    GAsyncResult *res,
    GError **error)
{
  GVariant *_ret;
  _ret = g_dbus_proxy_call_finish (G_DBUS_PROXY (proxy), res, error);
  if (_ret == NULL)
    goto _out;
  g_variant_get (_ret,
                 "()");
  g_variant_unref (_ret);
_out:
  return _ret != NULL;
}

/**
 * bamf_dbus_browser__call_show_tab_sync:
 * @proxy: A #BamfDBusBrowserProxy.
 * @arg_id: Argument to pass with the method invocation.
 * @cancellable: (allow-none): A #GCancellable or %NULL.
 * @error: Return location for error or %NULL.
 *
 * Synchronously invokes the <link linkend="gdbus-method-org-ayatana-bamf-browser.ShowTab">ShowTab()</link> D-Bus method on @proxy. The calling thread is blocked until a reply is received.
 *
 * See bamf_dbus_browser__call_show_tab() for the asynchronous version of this method.
 *
 * Returns: (skip): %TRUE if the call succeded, %FALSE if @error is set.
 */
gboolean
bamf_dbus_browser__call_show_tab_sync (
    BamfDBusBrowser *proxy,
    const gchar *arg_id,
    GCancellable *cancellable,
    GError **error)
{
  GVariant *_ret;
  _ret = g_dbus_proxy_call_sync (G_DBUS_PROXY (proxy),
    "ShowTab",
    g_variant_new ("(s)",
                   arg_id),
    G_DBUS_CALL_FLAGS_NONE,
    -1,
    cancellable,
    error);
  if (_ret == NULL)
    goto _out;
  g_variant_get (_ret,
                 "()");
  g_variant_unref (_ret);
_out:
  return _ret != NULL;
}

/**
 * bamf_dbus_browser__call_tab_uri:
 * @proxy: A #BamfDBusBrowserProxy.
 * @arg_id: Argument to pass with the method invocation.
 * @cancellable: (allow-none): A #GCancellable or %NULL.
 * @callback: A #GAsyncReadyCallback to call when the request is satisfied or %NULL.
 * @user_data: User data to pass to @callback.
 *
 * Asynchronously invokes the <link linkend="gdbus-method-org-ayatana-bamf-browser.TabUri">TabUri()</link> D-Bus method on @proxy.
 * When the operation is finished, @callback will be invoked in the <link linkend="g-main-context-push-thread-default">thread-default main loop</link> of the thread you are calling this method from.
 * You can then call bamf_dbus_browser__call_tab_uri_finish() to get the result of the operation.
 *
 * See bamf_dbus_browser__call_tab_uri_sync() for the synchronous, blocking version of this method.
 */
void
bamf_dbus_browser__call_tab_uri (
    BamfDBusBrowser *proxy,
    const gchar *arg_id,
    GCancellable *cancellable,
    GAsyncReadyCallback callback,
    gpointer user_data)
{
  g_dbus_proxy_call (G_DBUS_PROXY (proxy),
    "TabUri",
    g_variant_new ("(s)",
                   arg_id),
    G_DBUS_CALL_FLAGS_NONE,
    -1,
    cancellable,
    callback,
    user_data);
}

/**
 * bamf_dbus_browser__call_tab_uri_finish:
 * @proxy: A #BamfDBusBrowserProxy.
 * @out_uri: (out): Return location for return parameter or %NULL to ignore.
 * @res: The #GAsyncResult obtained from the #GAsyncReadyCallback passed to bamf_dbus_browser__call_tab_uri().
 * @error: Return location for error or %NULL.
 *
 * Finishes an operation started with bamf_dbus_browser__call_tab_uri().
 *
 * Returns: (skip): %TRUE if the call succeded, %FALSE if @error is set.
 */
gboolean
bamf_dbus_browser__call_tab_uri_finish (
    BamfDBusBrowser *proxy,
    gchar **out_uri,
    GAsyncResult *res,
    GError **error)
{
  GVariant *_ret;
  _ret = g_dbus_proxy_call_finish (G_DBUS_PROXY (proxy), res, error);
  if (_ret == NULL)
    goto _out;
  g_variant_get (_ret,
                 "(s)",
                 out_uri);
  g_variant_unref (_ret);
_out:
  return _ret != NULL;
}

/**
 * bamf_dbus_browser__call_tab_uri_sync:
 * @proxy: A #BamfDBusBrowserProxy.
 * @arg_id: Argument to pass with the method invocation.
 * @out_uri: (out): Return location for return parameter or %NULL to ignore.
 * @cancellable: (allow-none): A #GCancellable or %NULL.
 * @error: Return location for error or %NULL.
 *
 * Synchronously invokes the <link linkend="gdbus-method-org-ayatana-bamf-browser.TabUri">TabUri()</link> D-Bus method on @proxy. The calling thread is blocked until a reply is received.
 *
 * See bamf_dbus_browser__call_tab_uri() for the asynchronous version of this method.
 *
 * Returns: (skip): %TRUE if the call succeded, %FALSE if @error is set.
 */
gboolean
bamf_dbus_browser__call_tab_uri_sync (
    BamfDBusBrowser *proxy,
    const gchar *arg_id,
    gchar **out_uri,
    GCancellable *cancellable,
    GError **error)
{
  GVariant *_ret;
  _ret = g_dbus_proxy_call_sync (G_DBUS_PROXY (proxy),
    "TabUri",
    g_variant_new ("(s)",
                   arg_id),
    G_DBUS_CALL_FLAGS_NONE,
    -1,
    cancellable,
    error);
  if (_ret == NULL)
    goto _out;
  g_variant_get (_ret,
                 "(s)",
                 out_uri);
  g_variant_unref (_ret);
_out:
  return _ret != NULL;
}

/**
 * bamf_dbus_browser__call_tab_preview:
 * @proxy: A #BamfDBusBrowserProxy.
 * @arg_id: Argument to pass with the method invocation.
 * @cancellable: (allow-none): A #GCancellable or %NULL.
 * @callback: A #GAsyncReadyCallback to call when the request is satisfied or %NULL.
 * @user_data: User data to pass to @callback.
 *
 * Asynchronously invokes the <link linkend="gdbus-method-org-ayatana-bamf-browser.TabPreview">TabPreview()</link> D-Bus method on @proxy.
 * When the operation is finished, @callback will be invoked in the <link linkend="g-main-context-push-thread-default">thread-default main loop</link> of the thread you are calling this method from.
 * You can then call bamf_dbus_browser__call_tab_preview_finish() to get the result of the operation.
 *
 * See bamf_dbus_browser__call_tab_preview_sync() for the synchronous, blocking version of this method.
 */
void
bamf_dbus_browser__call_tab_preview (
    BamfDBusBrowser *proxy,
    const gchar *arg_id,
    GCancellable *cancellable,
    GAsyncReadyCallback callback,
    gpointer user_data)
{
  g_dbus_proxy_call (G_DBUS_PROXY (proxy),
    "TabPreview",
    g_variant_new ("(s)",
                   arg_id),
    G_DBUS_CALL_FLAGS_NONE,
    -1,
    cancellable,
    callback,
    user_data);
}

/**
 * bamf_dbus_browser__call_tab_preview_finish:
 * @proxy: A #BamfDBusBrowserProxy.
 * @out_preview: (out): Return location for return parameter or %NULL to ignore.
 * @res: The #GAsyncResult obtained from the #GAsyncReadyCallback passed to bamf_dbus_browser__call_tab_preview().
 * @error: Return location for error or %NULL.
 *
 * Finishes an operation started with bamf_dbus_browser__call_tab_preview().
 *
 * Returns: (skip): %TRUE if the call succeded, %FALSE if @error is set.
 */
gboolean
bamf_dbus_browser__call_tab_preview_finish (
    BamfDBusBrowser *proxy,
    gchar **out_preview,
    GAsyncResult *res,
    GError **error)
{
  GVariant *_ret;
  _ret = g_dbus_proxy_call_finish (G_DBUS_PROXY (proxy), res, error);
  if (_ret == NULL)
    goto _out;
  g_variant_get (_ret,
                 "(^ay)",
                 out_preview);
  g_variant_unref (_ret);
_out:
  return _ret != NULL;
}

/**
 * bamf_dbus_browser__call_tab_preview_sync:
 * @proxy: A #BamfDBusBrowserProxy.
 * @arg_id: Argument to pass with the method invocation.
 * @out_preview: (out): Return location for return parameter or %NULL to ignore.
 * @cancellable: (allow-none): A #GCancellable or %NULL.
 * @error: Return location for error or %NULL.
 *
 * Synchronously invokes the <link linkend="gdbus-method-org-ayatana-bamf-browser.TabPreview">TabPreview()</link> D-Bus method on @proxy. The calling thread is blocked until a reply is received.
 *
 * See bamf_dbus_browser__call_tab_preview() for the asynchronous version of this method.
 *
 * Returns: (skip): %TRUE if the call succeded, %FALSE if @error is set.
 */
gboolean
bamf_dbus_browser__call_tab_preview_sync (
    BamfDBusBrowser *proxy,
    const gchar *arg_id,
    gchar **out_preview,
    GCancellable *cancellable,
    GError **error)
{
  GVariant *_ret;
  _ret = g_dbus_proxy_call_sync (G_DBUS_PROXY (proxy),
    "TabPreview",
    g_variant_new ("(s)",
                   arg_id),
    G_DBUS_CALL_FLAGS_NONE,
    -1,
    cancellable,
    error);
  if (_ret == NULL)
    goto _out;
  g_variant_get (_ret,
                 "(^ay)",
                 out_preview);
  g_variant_unref (_ret);
_out:
  return _ret != NULL;
}

/**
 * bamf_dbus_browser__call_tab_xid:
 * @proxy: A #BamfDBusBrowserProxy.
 * @arg_id: Argument to pass with the method invocation.
 * @cancellable: (allow-none): A #GCancellable or %NULL.
 * @callback: A #GAsyncReadyCallback to call when the request is satisfied or %NULL.
 * @user_data: User data to pass to @callback.
 *
 * Asynchronously invokes the <link linkend="gdbus-method-org-ayatana-bamf-browser.TabXid">TabXid()</link> D-Bus method on @proxy.
 * When the operation is finished, @callback will be invoked in the <link linkend="g-main-context-push-thread-default">thread-default main loop</link> of the thread you are calling this method from.
 * You can then call bamf_dbus_browser__call_tab_xid_finish() to get the result of the operation.
 *
 * See bamf_dbus_browser__call_tab_xid_sync() for the synchronous, blocking version of this method.
 */
void
bamf_dbus_browser__call_tab_xid (
    BamfDBusBrowser *proxy,
    const gchar *arg_id,
    GCancellable *cancellable,
    GAsyncReadyCallback callback,
    gpointer user_data)
{
  g_dbus_proxy_call (G_DBUS_PROXY (proxy),
    "TabXid",
    g_variant_new ("(s)",
                   arg_id),
    G_DBUS_CALL_FLAGS_NONE,
    -1,
    cancellable,
    callback,
    user_data);
}

/**
 * bamf_dbus_browser__call_tab_xid_finish:
 * @proxy: A #BamfDBusBrowserProxy.
 * @out_xid: (out): Return location for return parameter or %NULL to ignore.
 * @res: The #GAsyncResult obtained from the #GAsyncReadyCallback passed to bamf_dbus_browser__call_tab_xid().
 * @error: Return location for error or %NULL.
 *
 * Finishes an operation started with bamf_dbus_browser__call_tab_xid().
 *
 * Returns: (skip): %TRUE if the call succeded, %FALSE if @error is set.
 */
gboolean
bamf_dbus_browser__call_tab_xid_finish (
    BamfDBusBrowser *proxy,
    guint *out_xid,
    GAsyncResult *res,
    GError **error)
{
  GVariant *_ret;
  _ret = g_dbus_proxy_call_finish (G_DBUS_PROXY (proxy), res, error);
  if (_ret == NULL)
    goto _out;
  g_variant_get (_ret,
                 "(u)",
                 out_xid);
  g_variant_unref (_ret);
_out:
  return _ret != NULL;
}

/**
 * bamf_dbus_browser__call_tab_xid_sync:
 * @proxy: A #BamfDBusBrowserProxy.
 * @arg_id: Argument to pass with the method invocation.
 * @out_xid: (out): Return location for return parameter or %NULL to ignore.
 * @cancellable: (allow-none): A #GCancellable or %NULL.
 * @error: Return location for error or %NULL.
 *
 * Synchronously invokes the <link linkend="gdbus-method-org-ayatana-bamf-browser.TabXid">TabXid()</link> D-Bus method on @proxy. The calling thread is blocked until a reply is received.
 *
 * See bamf_dbus_browser__call_tab_xid() for the asynchronous version of this method.
 *
 * Returns: (skip): %TRUE if the call succeded, %FALSE if @error is set.
 */
gboolean
bamf_dbus_browser__call_tab_xid_sync (
    BamfDBusBrowser *proxy,
    const gchar *arg_id,
    guint *out_xid,
    GCancellable *cancellable,
    GError **error)
{
  GVariant *_ret;
  _ret = g_dbus_proxy_call_sync (G_DBUS_PROXY (proxy),
    "TabXid",
    g_variant_new ("(s)",
                   arg_id),
    G_DBUS_CALL_FLAGS_NONE,
    -1,
    cancellable,
    error);
  if (_ret == NULL)
    goto _out;
  g_variant_get (_ret,
                 "(u)",
                 out_xid);
  g_variant_unref (_ret);
_out:
  return _ret != NULL;
}

/**
 * bamf_dbus_browser__complete_tab_ids:
 * @object: A #BamfDBusBrowser.
 * @invocation: (transfer full): A #GDBusMethodInvocation.
 * @ids: Parameter to return.
 *
 * Helper function used in service implementations to finish handling invocations of the <link linkend="gdbus-method-org-ayatana-bamf-browser.TabIds">TabIds()</link> D-Bus method. If you instead want to finish handling an invocation by returning an error, use g_dbus_method_invocation_return_error() or similar.
 *
 * This method will free @invocation, you cannot use it afterwards.
 */
void
bamf_dbus_browser__complete_tab_ids (
    BamfDBusBrowser *object,
    GDBusMethodInvocation *invocation,
    const gchar *const *ids)
{
  g_dbus_method_invocation_return_value (invocation,
    g_variant_new ("(^as)",
                   ids));
}

/**
 * bamf_dbus_browser__complete_show_tab:
 * @object: A #BamfDBusBrowser.
 * @invocation: (transfer full): A #GDBusMethodInvocation.
 *
 * Helper function used in service implementations to finish handling invocations of the <link linkend="gdbus-method-org-ayatana-bamf-browser.ShowTab">ShowTab()</link> D-Bus method. If you instead want to finish handling an invocation by returning an error, use g_dbus_method_invocation_return_error() or similar.
 *
 * This method will free @invocation, you cannot use it afterwards.
 */
void
bamf_dbus_browser__complete_show_tab (
    BamfDBusBrowser *object,
    GDBusMethodInvocation *invocation)
{
  g_dbus_method_invocation_return_value (invocation,
    g_variant_new ("()"));
}

/**
 * bamf_dbus_browser__complete_tab_uri:
 * @object: A #BamfDBusBrowser.
 * @invocation: (transfer full): A #GDBusMethodInvocation.
 * @uri: Parameter to return.
 *
 * Helper function used in service implementations to finish handling invocations of the <link linkend="gdbus-method-org-ayatana-bamf-browser.TabUri">TabUri()</link> D-Bus method. If you instead want to finish handling an invocation by returning an error, use g_dbus_method_invocation_return_error() or similar.
 *
 * This method will free @invocation, you cannot use it afterwards.
 */
void
bamf_dbus_browser__complete_tab_uri (
    BamfDBusBrowser *object,
    GDBusMethodInvocation *invocation,
    const gchar *uri)
{
  g_dbus_method_invocation_return_value (invocation,
    g_variant_new ("(s)",
                   uri));
}

/**
 * bamf_dbus_browser__complete_tab_preview:
 * @object: A #BamfDBusBrowser.
 * @invocation: (transfer full): A #GDBusMethodInvocation.
 * @preview: Parameter to return.
 *
 * Helper function used in service implementations to finish handling invocations of the <link linkend="gdbus-method-org-ayatana-bamf-browser.TabPreview">TabPreview()</link> D-Bus method. If you instead want to finish handling an invocation by returning an error, use g_dbus_method_invocation_return_error() or similar.
 *
 * This method will free @invocation, you cannot use it afterwards.
 */
void
bamf_dbus_browser__complete_tab_preview (
    BamfDBusBrowser *object,
    GDBusMethodInvocation *invocation,
    const gchar *preview)
{
  g_dbus_method_invocation_return_value (invocation,
    g_variant_new ("(^ay)",
                   preview));
}

/**
 * bamf_dbus_browser__complete_tab_xid:
 * @object: A #BamfDBusBrowser.
 * @invocation: (transfer full): A #GDBusMethodInvocation.
 * @xid: Parameter to return.
 *
 * Helper function used in service implementations to finish handling invocations of the <link linkend="gdbus-method-org-ayatana-bamf-browser.TabXid">TabXid()</link> D-Bus method. If you instead want to finish handling an invocation by returning an error, use g_dbus_method_invocation_return_error() or similar.
 *
 * This method will free @invocation, you cannot use it afterwards.
 */
void
bamf_dbus_browser__complete_tab_xid (
    BamfDBusBrowser *object,
    GDBusMethodInvocation *invocation,
    guint xid)
{
  g_dbus_method_invocation_return_value (invocation,
    g_variant_new ("(u)",
                   xid));
}

/* ------------------------------------------------------------------------ */

/**
 * BamfDBusBrowserProxy:
 *
 * The #BamfDBusBrowserProxy structure contains only private data and should only be accessed using the provided API.
 */

/**
 * BamfDBusBrowserProxyClass:
 * @parent_class: The parent class.
 *
 * Class structure for #BamfDBusBrowserProxy.
 */

struct _BamfDBusBrowserProxyPrivate
{
  GData *qdata;
};

static void bamf_dbus_browser__proxy_iface_init (BamfDBusBrowserIface *iface);

G_DEFINE_TYPE_WITH_CODE (BamfDBusBrowserProxy, bamf_dbus_browser__proxy, G_TYPE_DBUS_PROXY,
                         G_IMPLEMENT_INTERFACE (BAMF_DBUS_BROWSER_TYPE_, bamf_dbus_browser__proxy_iface_init));

static void
bamf_dbus_browser__proxy_finalize (GObject *object)
{
  BamfDBusBrowserProxy *proxy = BAMF_DBUS_BROWSER__PROXY (object);
  g_datalist_clear (&proxy->priv->qdata);
  G_OBJECT_CLASS (bamf_dbus_browser__proxy_parent_class)->finalize (object);
}

static void
bamf_dbus_browser__proxy_get_property (GObject      *object,
  guint         prop_id,
  GValue       *value,
  GParamSpec   *pspec)
{
}

static void
bamf_dbus_browser__proxy_set_property (GObject      *object,
  guint         prop_id,
  const GValue *value,
  GParamSpec   *pspec)
{
}

static void
bamf_dbus_browser__proxy_g_signal (GDBusProxy *proxy,
  const gchar *sender_name,
  const gchar *signal_name,
  GVariant *parameters)
{
  _ExtendedGDBusSignalInfo *info;
  GVariantIter iter;
  GVariant *child;
  GValue *paramv;
  guint num_params;
  guint n;
  guint signal_id;
  info = (_ExtendedGDBusSignalInfo *) g_dbus_interface_info_lookup_signal ((GDBusInterfaceInfo *) &_bamf_dbus_browser__interface_info, signal_name);
  if (info == NULL)
    return;
  num_params = g_variant_n_children (parameters);
  paramv = g_new0 (GValue, num_params + 1);
  g_value_init (&paramv[0], BAMF_DBUS_BROWSER_TYPE_);
  g_value_set_object (&paramv[0], proxy);
  g_variant_iter_init (&iter, parameters);
  n = 1;
  while ((child = g_variant_iter_next_value (&iter)) != NULL)
    {
      _ExtendedGDBusArgInfo *arg_info = (_ExtendedGDBusArgInfo *) info->parent_struct.args[n - 1];
      if (arg_info->use_gvariant)
        {
          g_value_init (&paramv[n], G_TYPE_VARIANT);
          g_value_set_variant (&paramv[n], child);
          n++;
        }
      else
        g_dbus_gvariant_to_gvalue (child, &paramv[n++]);
      g_variant_unref (child);
    }
  signal_id = g_signal_lookup (info->signal_name, BAMF_DBUS_BROWSER_TYPE_);
  g_signal_emitv (paramv, signal_id, 0, NULL);
  for (n = 0; n < num_params + 1; n++)
    g_value_unset (&paramv[n]);
  g_free (paramv);
}

static void
bamf_dbus_browser__proxy_g_properties_changed (GDBusProxy *_proxy,
  GVariant *changed_properties,
  const gchar *const *invalidated_properties)
{
  BamfDBusBrowserProxy *proxy = BAMF_DBUS_BROWSER__PROXY (_proxy);
  guint n;
  const gchar *key;
  GVariantIter *iter;
  _ExtendedGDBusPropertyInfo *info;
  g_variant_get (changed_properties, "a{sv}", &iter);
  while (g_variant_iter_next (iter, "{&sv}", &key, NULL))
    {
      info = (_ExtendedGDBusPropertyInfo *) g_dbus_interface_info_lookup_property ((GDBusInterfaceInfo *) &_bamf_dbus_browser__interface_info, key);
      g_datalist_remove_data (&proxy->priv->qdata, key);
      if (info != NULL)
        g_object_notify (G_OBJECT (proxy), info->hyphen_name);
    }
  g_variant_iter_free (iter);
  for (n = 0; invalidated_properties[n] != NULL; n++)
    {
      info = (_ExtendedGDBusPropertyInfo *) g_dbus_interface_info_lookup_property ((GDBusInterfaceInfo *) &_bamf_dbus_browser__interface_info, invalidated_properties[n]);
      g_datalist_remove_data (&proxy->priv->qdata, invalidated_properties[n]);
      if (info != NULL)
        g_object_notify (G_OBJECT (proxy), info->hyphen_name);
    }
}

static void
bamf_dbus_browser__proxy_init (BamfDBusBrowserProxy *proxy)
{
  proxy->priv = G_TYPE_INSTANCE_GET_PRIVATE (proxy, BAMF_DBUS_BROWSER_TYPE__PROXY, BamfDBusBrowserProxyPrivate);
  g_dbus_proxy_set_interface_info (G_DBUS_PROXY (proxy), bamf_dbus_browser__interface_info ());
}

static void
bamf_dbus_browser__proxy_class_init (BamfDBusBrowserProxyClass *klass)
{
  GObjectClass *gobject_class;
  GDBusProxyClass *proxy_class;

  g_type_class_add_private (klass, sizeof (BamfDBusBrowserProxyPrivate));

  gobject_class = G_OBJECT_CLASS (klass);
  gobject_class->finalize     = bamf_dbus_browser__proxy_finalize;
  gobject_class->get_property = bamf_dbus_browser__proxy_get_property;
  gobject_class->set_property = bamf_dbus_browser__proxy_set_property;

  proxy_class = G_DBUS_PROXY_CLASS (klass);
  proxy_class->g_signal = bamf_dbus_browser__proxy_g_signal;
  proxy_class->g_properties_changed = bamf_dbus_browser__proxy_g_properties_changed;

}

static void
bamf_dbus_browser__proxy_iface_init (BamfDBusBrowserIface *iface)
{
}

/**
 * bamf_dbus_browser__proxy_new:
 * @connection: A #GDBusConnection.
 * @flags: Flags from the #GDBusProxyFlags enumeration.
 * @name: (allow-none): A bus name (well-known or unique) or %NULL if @connection is not a message bus connection.
 * @object_path: An object path.
 * @cancellable: (allow-none): A #GCancellable or %NULL.
 * @callback: A #GAsyncReadyCallback to call when the request is satisfied.
 * @user_data: User data to pass to @callback.
 *
 * Asynchronously creates a proxy for the D-Bus interface <link linkend="gdbus-interface-org-ayatana-bamf-browser.top_of_page">org.ayatana.bamf.browser</link>. See g_dbus_proxy_new() for more details.
 *
 * When the operation is finished, @callback will be invoked in the <link linkend="g-main-context-push-thread-default">thread-default main loop</link> of the thread you are calling this method from.
 * You can then call bamf_dbus_browser__proxy_new_finish() to get the result of the operation.
 *
 * See bamf_dbus_browser__proxy_new_sync() for the synchronous, blocking version of this constructor.
 */
void
bamf_dbus_browser__proxy_new (
    GDBusConnection     *connection,
    GDBusProxyFlags      flags,
    const gchar         *name,
    const gchar         *object_path,
    GCancellable        *cancellable,
    GAsyncReadyCallback  callback,
    gpointer             user_data)
{
  g_async_initable_new_async (BAMF_DBUS_BROWSER_TYPE__PROXY, G_PRIORITY_DEFAULT, cancellable, callback, user_data, "g-flags", flags, "g-name", name, "g-connection", connection, "g-object-path", object_path, "g-interface-name", "org.ayatana.bamf.browser", NULL);
}

/**
 * bamf_dbus_browser__proxy_new_finish:
 * @res: The #GAsyncResult obtained from the #GAsyncReadyCallback passed to bamf_dbus_browser__proxy_new().
 * @error: Return location for error or %NULL
 *
 * Finishes an operation started with bamf_dbus_browser__proxy_new().
 *
 * Returns: (transfer full) (type BamfDBusBrowserProxy): The constructed proxy object or %NULL if @error is set.
 */
BamfDBusBrowser *
bamf_dbus_browser__proxy_new_finish (
    GAsyncResult        *res,
    GError             **error)
{
  GObject *ret;
  GObject *source_object;
  source_object = g_async_result_get_source_object (res);
  ret = g_async_initable_new_finish (G_ASYNC_INITABLE (source_object), res, error);
  g_object_unref (source_object);
  if (ret != NULL)
    return BAMF_DBUS_BROWSER_ (ret);
  else
    return NULL;
}

/**
 * bamf_dbus_browser__proxy_new_sync:
 * @connection: A #GDBusConnection.
 * @flags: Flags from the #GDBusProxyFlags enumeration.
 * @name: (allow-none): A bus name (well-known or unique) or %NULL if @connection is not a message bus connection.
 * @object_path: An object path.
 * @cancellable: (allow-none): A #GCancellable or %NULL.
 * @error: Return location for error or %NULL
 *
 * Synchronously creates a proxy for the D-Bus interface <link linkend="gdbus-interface-org-ayatana-bamf-browser.top_of_page">org.ayatana.bamf.browser</link>. See g_dbus_proxy_new_sync() for more details.
 *
 * The calling thread is blocked until a reply is received.
 *
 * See bamf_dbus_browser__proxy_new() for the asynchronous version of this constructor.
 *
 * Returns: (transfer full) (type BamfDBusBrowserProxy): The constructed proxy object or %NULL if @error is set.
 */
BamfDBusBrowser *
bamf_dbus_browser__proxy_new_sync (
    GDBusConnection     *connection,
    GDBusProxyFlags      flags,
    const gchar         *name,
    const gchar         *object_path,
    GCancellable        *cancellable,
    GError             **error)
{
  GInitable *ret;
  ret = g_initable_new (BAMF_DBUS_BROWSER_TYPE__PROXY, cancellable, error, "g-flags", flags, "g-name", name, "g-connection", connection, "g-object-path", object_path, "g-interface-name", "org.ayatana.bamf.browser", NULL);
  if (ret != NULL)
    return BAMF_DBUS_BROWSER_ (ret);
  else
    return NULL;
}


/**
 * bamf_dbus_browser__proxy_new_for_bus:
 * @bus_type: A #GBusType.
 * @flags: Flags from the #GDBusProxyFlags enumeration.
 * @name: A bus name (well-known or unique).
 * @object_path: An object path.
 * @cancellable: (allow-none): A #GCancellable or %NULL.
 * @callback: A #GAsyncReadyCallback to call when the request is satisfied.
 * @user_data: User data to pass to @callback.
 *
 * Like bamf_dbus_browser__proxy_new() but takes a #GBusType instead of a #GDBusConnection.
 *
 * When the operation is finished, @callback will be invoked in the <link linkend="g-main-context-push-thread-default">thread-default main loop</link> of the thread you are calling this method from.
 * You can then call bamf_dbus_browser__proxy_new_for_bus_finish() to get the result of the operation.
 *
 * See bamf_dbus_browser__proxy_new_for_bus_sync() for the synchronous, blocking version of this constructor.
 */
void
bamf_dbus_browser__proxy_new_for_bus (
    GBusType             bus_type,
    GDBusProxyFlags      flags,
    const gchar         *name,
    const gchar         *object_path,
    GCancellable        *cancellable,
    GAsyncReadyCallback  callback,
    gpointer             user_data)
{
  g_async_initable_new_async (BAMF_DBUS_BROWSER_TYPE__PROXY, G_PRIORITY_DEFAULT, cancellable, callback, user_data, "g-flags", flags, "g-name", name, "g-bus-type", bus_type, "g-object-path", object_path, "g-interface-name", "org.ayatana.bamf.browser", NULL);
}

/**
 * bamf_dbus_browser__proxy_new_for_bus_finish:
 * @res: The #GAsyncResult obtained from the #GAsyncReadyCallback passed to bamf_dbus_browser__proxy_new_for_bus().
 * @error: Return location for error or %NULL
 *
 * Finishes an operation started with bamf_dbus_browser__proxy_new_for_bus().
 *
 * Returns: (transfer full) (type BamfDBusBrowserProxy): The constructed proxy object or %NULL if @error is set.
 */
BamfDBusBrowser *
bamf_dbus_browser__proxy_new_for_bus_finish (
    GAsyncResult        *res,
    GError             **error)
{
  GObject *ret;
  GObject *source_object;
  source_object = g_async_result_get_source_object (res);
  ret = g_async_initable_new_finish (G_ASYNC_INITABLE (source_object), res, error);
  g_object_unref (source_object);
  if (ret != NULL)
    return BAMF_DBUS_BROWSER_ (ret);
  else
    return NULL;
}

/**
 * bamf_dbus_browser__proxy_new_for_bus_sync:
 * @bus_type: A #GBusType.
 * @flags: Flags from the #GDBusProxyFlags enumeration.
 * @name: A bus name (well-known or unique).
 * @object_path: An object path.
 * @cancellable: (allow-none): A #GCancellable or %NULL.
 * @error: Return location for error or %NULL
 *
 * Like bamf_dbus_browser__proxy_new_sync() but takes a #GBusType instead of a #GDBusConnection.
 *
 * The calling thread is blocked until a reply is received.
 *
 * See bamf_dbus_browser__proxy_new_for_bus() for the asynchronous version of this constructor.
 *
 * Returns: (transfer full) (type BamfDBusBrowserProxy): The constructed proxy object or %NULL if @error is set.
 */
BamfDBusBrowser *
bamf_dbus_browser__proxy_new_for_bus_sync (
    GBusType             bus_type,
    GDBusProxyFlags      flags,
    const gchar         *name,
    const gchar         *object_path,
    GCancellable        *cancellable,
    GError             **error)
{
  GInitable *ret;
  ret = g_initable_new (BAMF_DBUS_BROWSER_TYPE__PROXY, cancellable, error, "g-flags", flags, "g-name", name, "g-bus-type", bus_type, "g-object-path", object_path, "g-interface-name", "org.ayatana.bamf.browser", NULL);
  if (ret != NULL)
    return BAMF_DBUS_BROWSER_ (ret);
  else
    return NULL;
}


/* ------------------------------------------------------------------------ */

/**
 * BamfDBusBrowserSkeleton:
 *
 * The #BamfDBusBrowserSkeleton structure contains only private data and should only be accessed using the provided API.
 */

/**
 * BamfDBusBrowserSkeletonClass:
 * @parent_class: The parent class.
 *
 * Class structure for #BamfDBusBrowserSkeleton.
 */

struct _BamfDBusBrowserSkeletonPrivate
{
  GValue *properties;
  GList *changed_properties;
  GSource *changed_properties_idle_source;
  GMainContext *context;
  GMutex lock;
};

static void
_bamf_dbus_browser__skeleton_handle_method_call (
  GDBusConnection *connection,
  const gchar *sender,
  const gchar *object_path,
  const gchar *interface_name,
  const gchar *method_name,
  GVariant *parameters,
  GDBusMethodInvocation *invocation,
  gpointer user_data)
{
  BamfDBusBrowserSkeleton *skeleton = BAMF_DBUS_BROWSER__SKELETON (user_data);
  _ExtendedGDBusMethodInfo *info;
  GVariantIter iter;
  GVariant *child;
  GValue *paramv;
  guint num_params;
  guint num_extra;
  guint n;
  guint signal_id;
  GValue return_value = G_VALUE_INIT;
  info = (_ExtendedGDBusMethodInfo *) g_dbus_method_invocation_get_method_info (invocation);
  g_assert (info != NULL);
  num_params = g_variant_n_children (parameters);
  num_extra = info->pass_fdlist ? 3 : 2;  paramv = g_new0 (GValue, num_params + num_extra);
  n = 0;
  g_value_init (&paramv[n], BAMF_DBUS_BROWSER_TYPE_);
  g_value_set_object (&paramv[n++], skeleton);
  g_value_init (&paramv[n], G_TYPE_DBUS_METHOD_INVOCATION);
  g_value_set_object (&paramv[n++], invocation);
  if (info->pass_fdlist)
    {
#ifdef G_OS_UNIX
      g_value_init (&paramv[n], G_TYPE_UNIX_FD_LIST);
      g_value_set_object (&paramv[n++], g_dbus_message_get_unix_fd_list (g_dbus_method_invocation_get_message (invocation)));
#else
      g_assert_not_reached ();
#endif
    }
  g_variant_iter_init (&iter, parameters);
  while ((child = g_variant_iter_next_value (&iter)) != NULL)
    {
      _ExtendedGDBusArgInfo *arg_info = (_ExtendedGDBusArgInfo *) info->parent_struct.in_args[n - num_extra];
      if (arg_info->use_gvariant)
        {
          g_value_init (&paramv[n], G_TYPE_VARIANT);
          g_value_set_variant (&paramv[n], child);
          n++;
        }
      else
        g_dbus_gvariant_to_gvalue (child, &paramv[n++]);
      g_variant_unref (child);
    }
  signal_id = g_signal_lookup (info->signal_name, BAMF_DBUS_BROWSER_TYPE_);
  g_value_init (&return_value, G_TYPE_BOOLEAN);
  g_signal_emitv (paramv, signal_id, 0, &return_value);
  if (!g_value_get_boolean (&return_value))
    g_dbus_method_invocation_return_error (invocation, G_DBUS_ERROR, G_DBUS_ERROR_UNKNOWN_METHOD, "Method %s is not implemented on interface %s", method_name, interface_name);
  g_value_unset (&return_value);
  for (n = 0; n < num_params + num_extra; n++)
    g_value_unset (&paramv[n]);
  g_free (paramv);
}

static GVariant *
_bamf_dbus_browser__skeleton_handle_get_property (
  GDBusConnection *connection,
  const gchar *sender,
  const gchar *object_path,
  const gchar *interface_name,
  const gchar *property_name,
  GError **error,
  gpointer user_data)
{
  BamfDBusBrowserSkeleton *skeleton = BAMF_DBUS_BROWSER__SKELETON (user_data);
  GValue value = G_VALUE_INIT;
  GParamSpec *pspec;
  _ExtendedGDBusPropertyInfo *info;
  GVariant *ret;
  ret = NULL;
  info = (_ExtendedGDBusPropertyInfo *) g_dbus_interface_info_lookup_property ((GDBusInterfaceInfo *) &_bamf_dbus_browser__interface_info, property_name);
  g_assert (info != NULL);
  pspec = g_object_class_find_property (G_OBJECT_GET_CLASS (skeleton), info->hyphen_name);
  if (pspec == NULL)
    {
      g_set_error (error, G_DBUS_ERROR, G_DBUS_ERROR_INVALID_ARGS, "No property with name %s", property_name);
    }
  else
    {
      g_value_init (&value, pspec->value_type);
      g_object_get_property (G_OBJECT (skeleton), info->hyphen_name, &value);
      ret = g_dbus_gvalue_to_gvariant (&value, G_VARIANT_TYPE (info->parent_struct.signature));
      g_value_unset (&value);
    }
  return ret;
}

static gboolean
_bamf_dbus_browser__skeleton_handle_set_property (
  GDBusConnection *connection,
  const gchar *sender,
  const gchar *object_path,
  const gchar *interface_name,
  const gchar *property_name,
  GVariant *variant,
  GError **error,
  gpointer user_data)
{
  BamfDBusBrowserSkeleton *skeleton = BAMF_DBUS_BROWSER__SKELETON (user_data);
  GValue value = G_VALUE_INIT;
  GParamSpec *pspec;
  _ExtendedGDBusPropertyInfo *info;
  gboolean ret;
  ret = FALSE;
  info = (_ExtendedGDBusPropertyInfo *) g_dbus_interface_info_lookup_property ((GDBusInterfaceInfo *) &_bamf_dbus_browser__interface_info, property_name);
  g_assert (info != NULL);
  pspec = g_object_class_find_property (G_OBJECT_GET_CLASS (skeleton), info->hyphen_name);
  if (pspec == NULL)
    {
      g_set_error (error, G_DBUS_ERROR, G_DBUS_ERROR_INVALID_ARGS, "No property with name %s", property_name);
    }
  else
    {
      if (info->use_gvariant)
        g_value_set_variant (&value, variant);
      else
        g_dbus_gvariant_to_gvalue (variant, &value);
      g_object_set_property (G_OBJECT (skeleton), info->hyphen_name, &value);
      g_value_unset (&value);
      ret = TRUE;
    }
  return ret;
}

static const GDBusInterfaceVTable _bamf_dbus_browser__skeleton_vtable =
{
  _bamf_dbus_browser__skeleton_handle_method_call,
  _bamf_dbus_browser__skeleton_handle_get_property,
  _bamf_dbus_browser__skeleton_handle_set_property
};

static GDBusInterfaceInfo *
bamf_dbus_browser__skeleton_dbus_interface_get_info (GDBusInterfaceSkeleton *skeleton)
{
  return bamf_dbus_browser__interface_info ();
}

static GDBusInterfaceVTable *
bamf_dbus_browser__skeleton_dbus_interface_get_vtable (GDBusInterfaceSkeleton *skeleton)
{
  return (GDBusInterfaceVTable *) &_bamf_dbus_browser__skeleton_vtable;
}

static GVariant *
bamf_dbus_browser__skeleton_dbus_interface_get_properties (GDBusInterfaceSkeleton *_skeleton)
{
  BamfDBusBrowserSkeleton *skeleton = BAMF_DBUS_BROWSER__SKELETON (_skeleton);

  GVariantBuilder builder;
  guint n;
  g_variant_builder_init (&builder, G_VARIANT_TYPE ("a{sv}"));
  if (_bamf_dbus_browser__interface_info.parent_struct.properties == NULL)
    goto out;
  for (n = 0; _bamf_dbus_browser__interface_info.parent_struct.properties[n] != NULL; n++)
    {
      GDBusPropertyInfo *info = _bamf_dbus_browser__interface_info.parent_struct.properties[n];
      if (info->flags & G_DBUS_PROPERTY_INFO_FLAGS_READABLE)
        {
          GVariant *value;
          value = _bamf_dbus_browser__skeleton_handle_get_property (g_dbus_interface_skeleton_get_connection (G_DBUS_INTERFACE_SKELETON (skeleton)), NULL, g_dbus_interface_skeleton_get_object_path (G_DBUS_INTERFACE_SKELETON (skeleton)), "org.ayatana.bamf.browser", info->name, NULL, skeleton);
          if (value != NULL)
            {
              g_variant_take_ref (value);
              g_variant_builder_add (&builder, "{sv}", info->name, value);
              g_variant_unref (value);
            }
        }
    }
out:
  return g_variant_builder_end (&builder);
}

static void
bamf_dbus_browser__skeleton_dbus_interface_flush (GDBusInterfaceSkeleton *_skeleton)
{
}

static void
_bamf_dbus_browser__on_signal_tab_opened (
    BamfDBusBrowser *object,
    const gchar *arg_id)
{
  BamfDBusBrowserSkeleton *skeleton = BAMF_DBUS_BROWSER__SKELETON (object);

  GList      *connections, *l;
  GVariant   *signal_variant;
  connections = g_dbus_interface_skeleton_get_connections (G_DBUS_INTERFACE_SKELETON (skeleton));

  signal_variant = g_variant_ref_sink (g_variant_new ("(s)",
                   arg_id));
  for (l = connections; l != NULL; l = l->next)
    {
      GDBusConnection *connection = l->data;
      g_dbus_connection_emit_signal (connection,
        NULL, g_dbus_interface_skeleton_get_object_path (G_DBUS_INTERFACE_SKELETON (skeleton)), "org.ayatana.bamf.browser", "TabOpened",
        signal_variant, NULL);
    }
  g_variant_unref (signal_variant);
  g_list_free_full (connections, g_object_unref);
}

static void
_bamf_dbus_browser__on_signal_tab_closed (
    BamfDBusBrowser *object,
    const gchar *arg_id)
{
  BamfDBusBrowserSkeleton *skeleton = BAMF_DBUS_BROWSER__SKELETON (object);

  GList      *connections, *l;
  GVariant   *signal_variant;
  connections = g_dbus_interface_skeleton_get_connections (G_DBUS_INTERFACE_SKELETON (skeleton));

  signal_variant = g_variant_ref_sink (g_variant_new ("(s)",
                   arg_id));
  for (l = connections; l != NULL; l = l->next)
    {
      GDBusConnection *connection = l->data;
      g_dbus_connection_emit_signal (connection,
        NULL, g_dbus_interface_skeleton_get_object_path (G_DBUS_INTERFACE_SKELETON (skeleton)), "org.ayatana.bamf.browser", "TabClosed",
        signal_variant, NULL);
    }
  g_variant_unref (signal_variant);
  g_list_free_full (connections, g_object_unref);
}

static void
_bamf_dbus_browser__on_signal_tab_uri_changed (
    BamfDBusBrowser *object,
    const gchar *arg_id,
    const gchar *arg_old_uri,
    const gchar *arg_new_uri)
{
  BamfDBusBrowserSkeleton *skeleton = BAMF_DBUS_BROWSER__SKELETON (object);

  GList      *connections, *l;
  GVariant   *signal_variant;
  connections = g_dbus_interface_skeleton_get_connections (G_DBUS_INTERFACE_SKELETON (skeleton));

  signal_variant = g_variant_ref_sink (g_variant_new ("(sss)",
                   arg_id,
                   arg_old_uri,
                   arg_new_uri));
  for (l = connections; l != NULL; l = l->next)
    {
      GDBusConnection *connection = l->data;
      g_dbus_connection_emit_signal (connection,
        NULL, g_dbus_interface_skeleton_get_object_path (G_DBUS_INTERFACE_SKELETON (skeleton)), "org.ayatana.bamf.browser", "TabUriChanged",
        signal_variant, NULL);
    }
  g_variant_unref (signal_variant);
  g_list_free_full (connections, g_object_unref);
}

static void bamf_dbus_browser__skeleton_iface_init (BamfDBusBrowserIface *iface);
G_DEFINE_TYPE_WITH_CODE (BamfDBusBrowserSkeleton, bamf_dbus_browser__skeleton, G_TYPE_DBUS_INTERFACE_SKELETON,
                         G_IMPLEMENT_INTERFACE (BAMF_DBUS_BROWSER_TYPE_, bamf_dbus_browser__skeleton_iface_init));

static void
bamf_dbus_browser__skeleton_finalize (GObject *object)
{
  BamfDBusBrowserSkeleton *skeleton = BAMF_DBUS_BROWSER__SKELETON (object);
  g_list_free_full (skeleton->priv->changed_properties, (GDestroyNotify) _changed_property_free);
  if (skeleton->priv->changed_properties_idle_source != NULL)
    g_source_destroy (skeleton->priv->changed_properties_idle_source);
  g_main_context_unref (skeleton->priv->context);
  g_mutex_clear (&skeleton->priv->lock);
  G_OBJECT_CLASS (bamf_dbus_browser__skeleton_parent_class)->finalize (object);
}

static void
bamf_dbus_browser__skeleton_init (BamfDBusBrowserSkeleton *skeleton)
{
  skeleton->priv = G_TYPE_INSTANCE_GET_PRIVATE (skeleton, BAMF_DBUS_BROWSER_TYPE__SKELETON, BamfDBusBrowserSkeletonPrivate);
  g_mutex_init (&skeleton->priv->lock);
  skeleton->priv->context = g_main_context_ref_thread_default ();
}

static void
bamf_dbus_browser__skeleton_class_init (BamfDBusBrowserSkeletonClass *klass)
{
  GObjectClass *gobject_class;
  GDBusInterfaceSkeletonClass *skeleton_class;

  g_type_class_add_private (klass, sizeof (BamfDBusBrowserSkeletonPrivate));

  gobject_class = G_OBJECT_CLASS (klass);
  gobject_class->finalize = bamf_dbus_browser__skeleton_finalize;

  skeleton_class = G_DBUS_INTERFACE_SKELETON_CLASS (klass);
  skeleton_class->get_info = bamf_dbus_browser__skeleton_dbus_interface_get_info;
  skeleton_class->get_properties = bamf_dbus_browser__skeleton_dbus_interface_get_properties;
  skeleton_class->flush = bamf_dbus_browser__skeleton_dbus_interface_flush;
  skeleton_class->get_vtable = bamf_dbus_browser__skeleton_dbus_interface_get_vtable;
}

static void
bamf_dbus_browser__skeleton_iface_init (BamfDBusBrowserIface *iface)
{
  iface->tab_opened = _bamf_dbus_browser__on_signal_tab_opened;
  iface->tab_closed = _bamf_dbus_browser__on_signal_tab_closed;
  iface->tab_uri_changed = _bamf_dbus_browser__on_signal_tab_uri_changed;
}

/**
 * bamf_dbus_browser__skeleton_new:
 *
 * Creates a skeleton object for the D-Bus interface <link linkend="gdbus-interface-org-ayatana-bamf-browser.top_of_page">org.ayatana.bamf.browser</link>.
 *
 * Returns: (transfer full) (type BamfDBusBrowserSkeleton): The skeleton object.
 */
BamfDBusBrowser *
bamf_dbus_browser__skeleton_new (void)
{
  return BAMF_DBUS_BROWSER_ (g_object_new (BAMF_DBUS_BROWSER_TYPE__SKELETON, NULL));
}

